#!/bin/sh

export LD_LIBRARY_PATH=/home/bret/dev/pygem_diamond/pygem_diamond/pygem_diamond/lib
export DYLD_LIBRARY_PATH=/Users/bret/dev/pygem_diamond/pygem_diamond/pygem_diamond/lib
# set this to get around pthread issue on ubuntu (Bob's looking into it)
python bld_pygem.py --gemtype=diamond --casroot=~/dev/OpenCASCADE6.5.2 --esp=~/dev/EngSketchPad --gemroot=~/dev/GEM --bdist_egg --clean |& tee bld.out
#python bld_pygem.py --gemtype=diamond --casroot=~/dev/OCE/0.7.0 --esp=~/Downloads/EngSketchPad --gemroot=~/dev/GEM --bdist_egg --clean > bld.out 2>&1



